const PLAYERS = [
    { "id": 1, "name": "Michael Scott", "show": "The Office", "role": "Steve Carell", "img": "assets/characters/michael_scott.png" },
    { "id": 2, "name": "Dwight Schrute", "show": "The Office", "role": "Rainn Wilson", "img": "assets/characters/dwight_schrute.jpg" },
    { "id": 3, "name": "Jim Halpert", "show": "The Office", "role": "John Krasinski", "img": "assets/characters/jim_halpert.jpg" },
    { "id": 4, "name": "Pam Beesly", "show": "The Office", "role": "Jenna Fischer", "img": "assets/characters/pam_beesly.jpg" },
    { "id": 5, "name": "Walter White", "show": "Breaking Bad", "role": "Bryan Cranston", "img": "assets/characters/walter_white.png" },
    { "id": 6, "name": "Jesse Pinkman", "show": "Breaking Bad", "role": "Aaron Paul", "img": "assets/characters/jesse_pinkman.png" },
    { "id": 7, "name": "Eleven", "show": "Stranger Things", "role": "Millie Bobby Brown", "img": "assets/characters/eleven.png" },
    { "id": 8, "name": "Steve Harrington", "show": "Stranger Things", "role": "Joe Keery", "img": "assets/characters/steve_harrington.png" },
    { "id": 9, "name": "Tyrion Lannister", "show": "Game of Thrones", "role": "Peter Dinklage", "img": "assets/characters/tyrion_lannister.jpg" },
    { "id": 10, "name": "Daenerys Targaryen", "show": "Game of Thrones", "role": "Emilia Clarke", "img": "assets/characters/daenerys_targaryen.png" },
    { "id": 11, "name": "Carmy Berzatto", "show": "The Bear", "role": "Jeremy Allen White", "img": "assets/characters/carmy_berzatto.png" },
    { "id": 12, "name": "Sydney Adamu", "show": "The Bear", "role": "Ayo Edebiri", "img": "assets/characters/sydney_adamu.png" },
    { "id": 13, "name": "Jon Snow", "show": "Game of Thrones", "role": "Kit Harington", "img": "assets/characters/jon_snow.png" },
    { "id": 14, "name": "Gus Fring", "show": "Breaking Bad", "role": "Giancarlo Esposito", "img": "assets/characters/gus_fring.png" },
    { "id": 15, "name": "Saul Goodman", "show": "Better Call Saul", "role": "Bob Odenkirk", "img": "assets/characters/saul_goodman.png" },
    { "id": 16, "name": "Homelander", "show": "The Boys", "role": "Antony Starr", "img": "assets/characters/homelander.png" },
    { "id": 17, "name": "Billy Butcher", "show": "The Boys", "role": "Karl Urban", "img": "assets/characters/billy_butcher.png" },
    { "id": 18, "name": "Logan Roy", "show": "Succession", "role": "Brian Cox", "img": "assets/characters/logan_roy.png" },
    { "id": 19, "name": "Kendall Roy", "show": "Succession", "role": "Jeremy Strong", "img": "assets/characters/kendall_roy.png" },
    { "id": 20, "name": "Rick Grimes", "show": "The Walking Dead", "role": "Andrew Lincoln", "img": "assets/characters/rick_grimes.jpg?v=3" },
    { "id": 21, "name": "Daryl Dixon", "show": "The Walking Dead", "role": "Norman Reedus", "img": "assets/characters/daryl_dixon.jpg" },
    { "id": 22, "name": "Harvey Specter", "show": "Suits", "role": "Gabriel Macht", "img": "assets/characters/harvey_specter.jpg?v=2" },
    { "id": 23, "name": "Mike Ross", "show": "Suits", "role": "Patrick J. Adams", "img": "assets/characters/mike_ross.jpg?v=2" },
    { "id": 24, "name": "Jax Teller", "show": "Sons of Anarchy", "role": "Charlie Hunnam", "img": "assets/characters/jax_teller.jpg?v=2" },
    { "id": 25, "name": "Clay Morrow", "show": "Sons of Anarchy", "role": "Ron Perlman", "img": "assets/characters/clay_morrow.jpg" },
];
