const PLAYERS = [
    { "id": 1, "name": "Michael Scott", "show": "The Office", "role": "Steve Carell", "img": "assets/characters/michael_scott.png" },
    { "id": 2, "name": "Dwight Schrute", "show": "The Office", "role": "Rainn Wilson", "img": "assets/characters/dwight_schrute.jpg" },
    { "id": 3, "name": "Jim Halpert", "show": "The Office", "role": "John Krasinski", "img": "assets/characters/jim_halpert.jpg" },
    { "id": 4, "name": "Pam Beesly", "show": "The Office", "role": "Jenna Fischer", "img": "assets/characters/pam_beesly.jpg" },
    { "id": 5, "name": "Walter White", "show": "Breaking Bad", "role": "Bryan Cranston", "img": "assets/characters/walter_white.png" },
    { "id": 6, "name": "Jesse Pinkman", "show": "Breaking Bad", "role": "Aaron Paul", "img": "assets/characters/jesse_pinkman.png" },
    { "id": 7, "name": "Eleven", "show": "Stranger Things", "role": "Millie Bobby Brown", "img": "assets/characters/eleven.png" },
    { "id": 8, "name": "Steve Harrington", "show": "Stranger Things", "role": "Joe Keery", "img": "assets/characters/steve_harrington.png" },
    { "id": 9, "name": "Tyrion Lannister", "show": "Game of Thrones", "role": "Peter Dinklage", "img": "assets/characters/tyrion_lannister.jpg" },
    { "id": 10, "name": "Daenerys Targaryen", "show": "Game of Thrones", "role": "Emilia Clarke", "img": "assets/characters/daenerys_targaryen.png" },
    { "id": 11, "name": "Carmy Berzatto", "show": "The Bear", "role": "Jeremy Allen White", "img": "assets/characters/carmy_berzatto.png" },
    { "id": 12, "name": "Sydney Adamu", "show": "The Bear", "role": "Ayo Edebiri", "img": "assets/characters/sydney_adamu.png" },
    { "id": 13, "name": "Jon Snow", "show": "Game of Thrones", "role": "Kit Harington", "img": "assets/characters/jon_snow.png" },
    { "id": 14, "name": "Gus Fring", "show": "Breaking Bad", "role": "Giancarlo Esposito", "img": "assets/characters/gus_fring.png" },
    { "id": 15, "name": "Saul Goodman", "show": "Better Call Saul", "role": "Bob Odenkirk", "img": "assets/characters/saul_goodman.png" },
    { "id": 16, "name": "Homelander", "show": "The Boys", "role": "Antony Starr", "img": "assets/characters/homelander.png" },
    { "id": 17, "name": "Billy Butcher", "show": "The Boys", "role": "Karl Urban", "img": "assets/characters/billy_butcher.png" },
    { "id": 18, "name": "Logan Roy", "show": "Succession", "role": "Brian Cox", "img": "assets/characters/logan_roy.png" },
    { "id": 19, "name": "Kendall Roy", "show": "Succession", "role": "Jeremy Strong", "img": "assets/characters/kendall_roy.png" },
    { "id": 20, "name": "Rick Grimes", "show": "The Walking Dead", "role": "Andrew Lincoln", "img": "assets/characters/rick_grimes.jpg" },
    { "id": 21, "name": "Daryl Dixon", "show": "The Walking Dead", "role": "Norman Reedus", "img": "assets/characters/daryl_dixon.jpg" },
    { "id": 22, "name": "Harvey Specter", "show": "Suits", "role": "Gabriel Macht", "img": "assets/characters/harvey_specter.jpg" },
    { "id": 23, "name": "Mike Ross", "show": "Suits", "role": "Patrick J. Adams", "img": "assets/characters/mike_ross.jpg" },
    { "id": 24, "name": "Jax Teller", "show": "Sons of Anarchy", "role": "Charlie Hunnam", "img": "assets/characters/jax_teller.jpg" },
    { "id": 25, "name": "Clay Morrow", "show": "Sons of Anarchy", "role": "Ron Perlman", "img": "assets/characters/clay_morrow.jpg" },
    { "id": 26, "name": "Opie Winston", "show": "Sons of Anarchy", "role": "Ryan Hurst", "img": "assets/characters/jax_teller.jpg" },
    { "id": 27, "name": "Gemma Teller", "show": "Sons of Anarchy", "role": "Katey Sagal", "img": "assets/characters/jax_teller.jpg" },
    { "id": 28, "name": "Starlight", "show": "The Boys", "role": "Erin Moriarty", "img": "assets/characters/homelander.png" },
    { "id": 29, "name": "A-Train", "show": "The Boys", "role": "Jessie T. Usher", "img": "assets/characters/homelander.png" },
    { "id": 30, "name": "Shiv Roy", "show": "Succession", "role": "Sarah Snook", "img": "assets/characters/kendall_roy.png" },
    { "id": 31, "name": "Roman Roy", "show": "Succession", "role": "Kieran Culkin", "img": "assets/characters/kendall_roy.png" },
    { "id": 32, "name": "Michonne", "show": "The Walking Dead", "role": "Danai Gurira", "img": "assets/characters/rick_grimes.jpg" },
    { "id": 33, "name": "Glenn Rhee", "show": "The Walking Dead", "role": "Steven Yeun", "img": "assets/characters/rick_grimes.jpg" },
    { "id": 34, "name": "Rachel Zane", "show": "Suits", "role": "Meghan Markle", "img": "assets/characters/mike_ross.jpg" },
    { "id": 35, "name": "Louis Litt", "show": "Suits", "role": "Rick Hoffman", "img": "assets/characters/mike_ross.jpg" },
    { "id": 36, "name": "Richie Jerimovich", "show": "The Bear", "role": "Ebon Moss-Bachrach", "img": "assets/characters/carmy_berzatto.png" },
    { "id": 37, "name": "Marcus Brooks", "show": "The Bear", "role": "Lionel Boyce", "img": "assets/characters/carmy_berzatto.png" },
    
    // MYTHIC CARDS (Not in packs)
    { "id": 101, "name": "Heisenberg", "show": "Breaking Bad", "role": "The Kingpin", "img": "assets/characters/mythic_heisenberg.png", "rarity": "Mythic" },
    { "id": 102, "name": "Prison Mike", "show": "The Office", "role": "The Convict", "img": "assets/characters/mythic_prison_mike.png", "rarity": "Mythic" },
    { "id": 103, "name": "Mother of Dragons", "show": "Game of Thrones", "role": "Breaker of Chains", "img": "assets/characters/mythic_daenerys.png", "rarity": "Mythic" },
    { "id": 104, "name": "Jane Hopper (011)", "show": "Stranger Things", "role": "The Powerful One", "img": "assets/characters/mythic_eleven.png", "rarity": "Mythic" },
    { "id": 105, "name": "Chef de Cuisine", "show": "The Bear", "role": "The Bear", "img": "assets/characters/mythic_carmy.png", "rarity": "Mythic" },
    { "id": 106, "name": "Homelander Unchained", "show": "The Boys", "role": "The Pure Villain", "img": "assets/characters/mythic_homelander.png", "rarity": "Mythic" },
    { "id": 107, "name": "CEO Kendall Roy", "show": "Succession", "role": "L to the OG", "img": "assets/characters/mythic_kendall.png", "rarity": "Mythic" },
    { "id": 108, "name": "Sheriff Rick Grimes", "show": "The Walking Dead", "role": "Ultimate Survivor", "img": "assets/characters/mythic_rick.png", "rarity": "Mythic" },
    { "id": 109, "name": "The Closer: Harvey", "show": "Suits", "role": "Managing Partner", "img": "assets/characters/mythic_harvey.png", "rarity": "Mythic" },
    { "id": 110, "name": "President Jax", "show": "Sons of Anarchy", "role": "Final Ride", "img": "assets/characters/mythic_jax.png", "rarity": "Mythic" },
    { "id": 111, "name": "Gene Takavic", "show": "Better Call Saul", "role": "Cinnabon Manager", "img": "assets/characters/mythic_gene.png", "rarity": "Mythic" }
];
